### ISSUE TITLE
JSONDecodeError during the CSV files generation

### ISSUE THREAD

**Issue by PyyLog** [ipsa-scrypt/data-forge#3]
The problem happens depending the number of observation we want to generate in our dataset.

For example, when we generate 5 observations, the program doesn't throw an error.
When we want to generate more observations (for instance 30 in the screens below), then the error pops out.

<img width="716" alt="image" src="https://github.com/ipsa-scrypt/data-forge/assets/78143876/0404a857-913d-4043-8508-ad7404c7c09a">

<img width="718" alt="image" src="https://github.com/ipsa-scrypt/data-forge/assets/78143876/9c91bb62-1c83-4bf8-b1eb-66a08c6d1b45">

**Comment by PhantHive** [comment]
It seems like the error happen when the openAI completion is stopping maybe.

Suggestion:

- Add a breakpoint on the openAI completion process to see what is returned at last.

- Try to check if the API support a feature to keep completing even after a sudden break.

- Except the specific error and call again openAI
